# Meta Data for SEO

## Homepage
title = "TLA"
titleSeparator = "-"
titleAddition = "TiDE Learning Accelerator"
description = "This is the online home of the Technology in Disaster Environments (TiDE) Learning Accelerator (TLA)"

## Open Graph
images = ["images/logo_with_title.png"]
ogLocale = "en_US"
domainTLD = "doks.netlify.app"
titleHome = "TiDE Learning Accelerator"

## Twitter Cards
twitterSite = "@iuctil"
twitterCreator = "@iuctil"

## JSON-LD
schemaType = "Organization"
schemaName = "IU/CTIL"
schemaAuthor = "Soichi Hayashi"
schemaAuthorTwitter = "https://twitter.com/soichih"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/soichih/"
schemaAuthorGitHub = "https://github.com/soichih"
schemaLocale = "en-US"
schemaLogo = "images/logox478.png"
schemaLogoWidth = 478
schemaLogoHeight = 478
schemaImage = "images/logo_with_titlex1500.png"
schemaImageWidth = 1943
schemaImageHeight = 479
schemaTwitter = "https://twitter.com/iuctil"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/iuctil"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by <a href=\"https://ctil.iu.edu/\">Crisis Technologies Innovation Lab</a> at <a href=\"https://iu.edu/\">Indiana University</a>"
copyRight = "Copyright (c) 2020-2021 Henk Verlinde"

# Alert
alert = false
alertText = "Like Doks? <a class=\"alert-link\" href=\"https://github.com/h-enk/doks/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/iuctil/tla"
editPage = true

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  collapsibleSidebar = false

